version: "3.9"

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  django:
    build:
      context: ./backend
      target: "base"
    restart: always
    expose:
      - 8000
    volumes:
      - ./backend/djangoapp:/usr/src/app
      - django-static-volume:/usr/src/app/static
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  react:
    build:
      context: ./frontend
      target: "base"
    stdin_open: true
    expose:
      - 3000
    command: npm run dev
    volumes:
      - ./frontend/react:/usr/src/app
      - /usr/src/node_modules
    depends_on:
      - django

  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - django-static-volume:/usr/src/app/django/static
    ports:
      - 80:80
    depends_on:
      - react

volumes:
  postgres-data:
  django-static-volume:
