# Generated by Django 3.2.9 on 2021-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211207_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='circle',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circle',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='circle',
            name='diameter',
            field=models.IntegerField(default=50),
        ),
    ]
